// Auto-generated project data from images (Updated with correct image paths and addresses)
// Generated on: 2025-08-01T20:47:22.873Z

import { ProjectDetail } from "../types/projectCategoryPageTypes";

export const additionalProjectData: {
  appartment: ProjectDetail[];
  "house-normal": ProjectDetail[];
  village: ProjectDetail[];
  "house-business": ProjectDetail[];
} = {
  appartment: [
    {
      id: 1,
      projectId: "APPARTMENT001",
      title: "Căn hộ PHÚ GIA HƯNG",
      clientName: "ANH ĐĂNG",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "GÒ VẤP",
      description:
        "Thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-01.png",
      htmlContent:
        "<div><h3>Thiết Kế PHÚ GIA HƯNG</h3><p>Dự án thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-01.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-02.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-03.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-04.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-05.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-06.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-07.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-08.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-09.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-10.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-11.png",
        "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-12.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế PHÚ GIA HƯNG",
      metaDescription: "Thiết kế căn hộ tại GÒ VẤP",
      tags: ["căn hộ", "nội thất", "hiện đại", "GÒ VẤP"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    {
      id: 2,
      projectId: "APPARTMENT002",
      title: "Căn hộ OPAL GARDEN",
      clientName: "ANH LONG",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "HIỆP BÌNH HCM",
      description:
        "Thiết kế căn hộ tại HIỆP BÌNH HCM với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/0.png",
      htmlContent:
        "<div><h3>Thiết Kế OPAL GARDEN</h3><p>Dự án thiết kế căn hộ tại HIỆP BÌNH HCM với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/0.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/1.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/2.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/3.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/4.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/5.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/6.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/7.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/8.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/9.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/10.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/11.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/12.png",
        "/assets/appartment/ANH LONG - OPAL GARDEN - HIỆP BÌNH HCM/13.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế OPAL GARDEN",
      metaDescription: "Thiết kế căn hộ tại HIỆP BÌNH HCM",
      tags: ["căn hộ", "nội thất", "hiện đại", "HIỆP BÌNH HCM"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    {
      id: 3,
      projectId: "APPARTMENT003",
      title: "Căn hộ DIAMOND",
      clientName: "CHỊ NHI",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "TÂN PHÚ",
      description:
        "Thiết kế căn hộ tại TÂN PHÚ với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage: "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/0.png",
      htmlContent:
        "<div><h3>Thiết Kế DIAMOND</h3><p>Dự án thiết kế căn hộ tại TÂN PHÚ với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/0.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/1.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/2.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/3.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/4.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/5.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/6.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/7.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/8.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/9.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/10.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/11.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/12.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/13.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/14.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/15.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/16.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/17.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/18.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/19.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/20.png",
        "/assets/appartment/CHỊ NHI - DIAMOND - TÂN PHÚ/21.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế DIAMOND",
      metaDescription: "Thiết kế căn hộ tại TÂN PHÚ",
      tags: ["căn hộ", "nội thất", "hiện đại", "TÂN PHÚ"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    {
      id: 4,
      projectId: "APPARTMENT004",
      title: "Căn hộ CITYLAND PARK HILL",
      clientName: "ANH TUẤN",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "GÒ VẤP",
      description:
        "Thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/1.png",
      htmlContent:
        "<div><h3>Thiết Kế CITYLAND PARK HILL</h3><p>Dự án thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/1.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/2.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/3.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/4.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/5.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/6.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/7.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/8.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/9.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/11.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/13.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/15.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/17.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/18.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/19.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/21.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/22.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/23.png",
        "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL - GÒ VẤP/24.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế CITYLAND PARK HILL",
      metaDescription: "Thiết kế căn hộ tại GÒ VẤP",
      tags: ["căn hộ", "nội thất", "hiện đại", "GÒ VẤP"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 5,
      projectId: "APPARTMENT005",
      title: "Căn hộ URBAN",
      clientName: "CHỊ THUY",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "hIỆP bÌNH HCM",
      description:
        "Thiết kế căn hộ tại hIỆP bÌNH HCM với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/0.png",
      htmlContent:
        "<div><h3>Thiết Kế URBAN</h3><p>Dự án thiết kế căn hộ tại hIỆP bÌNH HCM với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/0.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/1.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/2.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/3.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/4.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/5.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/6.png",
        "/assets/appartment/CHỊ THUY - URBAN - hIỆP bÌNH HCM/7.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế URBAN",
      metaDescription: "Thiết kế căn hộ tại hIỆP bÌNH HCM",
      tags: ["căn hộ", "nội thất", "hiện đại", "hIỆP bÌNH HCM"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 6,
      projectId: "APPARTMENT006",
      title: "Căn hộ Midoripark The Glory",
      clientName: "CHỊ LINH",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "BINH DUONG",
      description:
        "Thiết kế căn hộ tại BINH DUONG với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/1.png",
      htmlContent:
        "<div><h3>Thiết Kế Midoripark The Glory</h3><p>Dự án thiết kế căn hộ tại BINH DUONG với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/1.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/2.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/3.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/4.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/5.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/6.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/7.png",
        "/assets/appartment/CHỊ LINH - Midoripark The Glory - BINH DUONG/8.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Midoripark The Glory",
      metaDescription: "Thiết kế căn hộ tại BINH DUONG",
      tags: ["căn hộ", "nội thất", "hiện đại", "BINH DUONG"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 7,
      projectId: "APPARTMENT007",
      title: "Căn hộ PEGASUITE",
      clientName: "CHỊ HA",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "Q8",
      description:
        "Thiết kế căn hộ tại Q8 với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage: "/assets/appartment/CHỊ HA - PEGASUITE - Q8/1.png",
      htmlContent:
        "<div><h3>Thiết Kế PEGASUITE</h3><p>Dự án thiết kế căn hộ tại Q8 với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/1.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/2.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/3.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/4.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/5.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/6.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/7.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/8.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/9.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/10.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/11.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/12.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/13.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/14.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/15.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/16.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/17.png",
        "/assets/appartment/CHỊ HA - PEGASUITE - Q8/18.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế PEGASUITE",
      metaDescription: "Thiết kế căn hộ tại Q8",
      tags: ["căn hộ", "nội thất", "hiện đại", "Q8"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 8,
      projectId: "APPARTMENT008",
      title: "Căn hộ PICITY",
      clientName: "ANH PHÚC",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "Q12",
      description:
        "Thiết kế căn hộ tại Q12 với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-01.png",
      htmlContent:
        "<div><h3>Thiết Kế PICITY</h3><p>Dự án thiết kế căn hộ tại Q12 với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-01.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-02.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-03.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-04.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-05.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-06.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-07.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-08.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-09.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-10.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-11.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-12.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-13.png",
        "/assets/appartment/ANH PHÚC - PICITY - Q12/picity-q12-14.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế PICITY",
      metaDescription: "Thiết kế căn hộ tại Q12",
      tags: ["căn hộ", "nội thất", "hiện đại", "Q12"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 9,
      projectId: "APPARTMENT009",
      title: "Căn hộ CITYGATE",
      clientName: "CHỊ LAN",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "Q8",
      description:
        "Thiết kế căn hộ tại Q8 với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage: "/assets/appartment/CHỊ LAN - CITYGATE - Q8/1.png",
      htmlContent:
        "<div><h3>Thiết Kế CITYGATE</h3><p>Dự án thiết kế căn hộ tại Q8 với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/1.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/2.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/3.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/4.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/5.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/6.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/7.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/8.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/9.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/10.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/11.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/12.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/13.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/14.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/15.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/16.png",
        "/assets/appartment/CHỊ LAN - CITYGATE - Q8/17.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế CITYGATE",
      metaDescription: "Thiết kế căn hộ tại Q8",
      tags: ["căn hộ", "nội thất", "hiện đại", "Q8"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 10,
      projectId: "APPARTMENT010",
      title: "Căn hộ CITYLAND PARK HILL",
      clientName: "ANH MINH",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "GÒ VẤP",
      description:
        "Thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại và tiện nghi.",
      category: "appartment",
      projectCategoryId: 2,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/0.png",
      htmlContent:
        "<div><h3>Thiết Kế CITYLAND PARK HILL</h3><p>Dự án thiết kế căn hộ tại GÒ VẤP với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/0.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/1.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/2.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/3.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/4.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/5.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/6.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/7.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/8.png",
        "/assets/appartment/ANH MINH - CITYLAND PARK HILL - GÒ VẤP/9.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế CITYLAND PARK HILL",
      metaDescription: "Thiết kế căn hộ tại GÒ VẤP",
      tags: ["căn hộ", "nội thất", "hiện đại", "GÒ VẤP"],
      isOnHomePage: true,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
  ],
  "house-normal": [
    {
      id: 11,
      projectId: "HOUSE-NORMAL011",
      title: "Nhà phố LONG AN",
      clientName: "CHỊ MƠ",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "INDOCHINE",
      description:
        "Thiết kế nhà phố tại INDOCHINE với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/1.png",
      htmlContent:
        "<div><h3>Thiết Kế LONG AN</h3><p>Dự án thiết kế nhà phố tại INDOCHINE với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/1.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/2.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/3.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/4.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/5.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/6.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/7.png",
        "/assets/house-normal/CHỊ MƠ - LONG AN - INDOCHINE/8.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế LONG AN",
      metaDescription: "Thiết kế nhà phố tại INDOCHINE",
      tags: ["nhà phố", "nội thất", "hiện đại", "INDOCHINE"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    {
      id: 12,
      projectId: "HOUSE-NORMAL012",
      title: "Nhà phố QUẬN 7",
      clientName: "CHỊ HƯƠNG",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "QUẬN 7",
      description:
        "Thiết kế nhà phố tại QUẬN 7 với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/1.png",
      htmlContent:
        "<div><h3>Thiết Kế QUẬN 7</h3><p>Dự án thiết kế nhà phố tại QUẬN 7 với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/1.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/2.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/3.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/4.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/6.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/7.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/8.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/9.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/10.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/11.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/12.png",
        "/assets/house-normal/CHỊ HƯƠNG - QUẬN 7/13.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế QUẬN 7",
      metaDescription: "Thiết kế nhà phố tại QUẬN 7",
      tags: ["nhà phố", "nội thất", "hiện đại", "QUẬN 7"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    {
      id: 13,
      projectId: "HOUSE-NORMAL013",
      title: "Nhà phố LONG THÀNH",
      clientName: "ANH SƠN",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "LONG THÀNH",
      description:
        "Thiết kế nhà phố tại LONG THÀNH với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-01.png",
      htmlContent:
        "<div><h3>Thiết Kế LONG THÀNH</h3><p>Dự án thiết kế nhà phố tại LONG THÀNH với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-01.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-02.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-03.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-04.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-05.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-06.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-07.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-08.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-09.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-10.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-11.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-12.png",
        "/assets/house-normal/ANH SƠN - LONG THÀNH/nha-pho-long-thanh-13.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế LONG THÀNH",
      metaDescription: "Thiết kế nhà phố tại LONG THÀNH",
      tags: ["nhà phố", "nội thất", "hiện đại", "LONG THÀNH"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
      subCategory: "",
    },
    // {
    //   id: 14,
    //   projectId: "HOUSE-NORMAL014",
    //   title: "Nhà phố NHÀ BÈ",
    //   clientName: "CHỊ THẢO",
    //   area: "110m²",
    //   constructionDate: "2024-01-01",
    //   address: "NHÀ BÈ",
    //   description:
    //     "Thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại và tiện nghi.",
    //   category: "house-normal",
    //   projectCategoryId: 1,
    //   style: "Hiện đại",
    //   thumbnailImage:
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-01.png",
    //   htmlContent:
    //     "<div><h3>Thiết Kế NHÀ BÈ</h3><p>Dự án thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
    //   projectImages: [
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-01.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-02.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-03.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-04.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-05.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-06.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-07.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-08.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-09.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-10.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-11.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-12.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-13.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-14.png",
    //     "/assets/house-normal/CHỊ THẢO - NHÀ BÈ/nha-pho-nha-be-15.png",
    //   ],
    //   projectStatus: "Hoàn thành • 500 triệu",
    //   completionDate: "2024-06-30",
    //   architectName: "KTS. PG Design",
    //   contractorName: "PG Design",
    //   metaTitle: "Thiết Kế NHÀ BÈ",
    //   metaDescription: "Thiết kế nhà phố tại NHÀ BÈ",
    //   tags: ["nhà phố", "nội thất", "hiện đại", "NHÀ BÈ"],
    //   isOnHomePage: false,
    //   isActive: true,
    //   createdAt: "2024-01-01T00:00:00Z",
    //   updatedAt: "2024-06-30T00:00:00Z",
    // },
    {
      id: 15,
      projectId: "HOUSE-NORMAL015",
      title: "Nhà phố TIỀN GIANG",
      clientName: "ANH NAM",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "TIỀN GIANG",
      description:
        "Thiết kế nhà phố tại TIỀN GIANG với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/ANH NAM - TIỀN GIANG/1.png",
      htmlContent:
        "<div><h3>Thiết Kế TIỀN GIANG</h3><p>Dự án thiết kế nhà phố tại TIỀN GIANG với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/ANH NAM - TIỀN GIANG/1.png",
        "/assets/house-normal/ANH NAM - TIỀN GIANG/2.png",
        "/assets/house-normal/ANH NAM - TIỀN GIANG/3.png",
        "/assets/house-normal/ANH NAM - TIỀN GIANG/4.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế TIỀN GIANG",
      metaDescription: "Thiết kế nhà phố tại TIỀN GIANG",
      tags: ["nhà phố", "nội thất", "hiện đại", "TIỀN GIANG"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 16,
      projectId: "HOUSE-NORMAL016",
      title: "Nhà phố DONG NAI",
      clientName: "CHỊ NGOC",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "DONG NAI",
      description:
        "Thiết kế nhà phố tại DONG NAI với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/CHỊ NGOC - DONG NAI/1.png",
      htmlContent:
        "<div><h3>Thiết Kế DONG NAI</h3><p>Dự án thiết kế nhà phố tại DONG NAI với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/CHỊ NGOC - DONG NAI/1.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/2.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/3.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/4.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/5.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/6.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/7.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/8.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/9.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/10.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/11.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/12.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/13.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/14.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/15.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/16.png",
        "/assets/house-normal/CHỊ NGOC - DONG NAI/25.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế DONG NAI",
      metaDescription: "Thiết kế nhà phố tại DONG NAI",
      tags: ["nhà phố", "nội thất", "hiện đại", "DONG NAI"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 17,
      projectId: "HOUSE-NORMAL017",
      title: "Nhà phố NHÀ BÈ",
      clientName: "ANH HƯNG",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "NHÀ BÈ",
      description:
        "Thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/ANH HƯNG - NHÀ BÈ/1.png",
      htmlContent:
        "<div><h3>Thiết Kế NHÀ BÈ</h3><p>Dự án thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/1.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/2.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/3.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/4.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/5.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/6.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/7.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/8.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/9.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/10.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/11.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/12.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/13.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/14.png",
        "/assets/house-normal/ANH HƯNG - NHÀ BÈ/15.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế NHÀ BÈ",
      metaDescription: "Thiết kế nhà phố tại NHÀ BÈ",
      tags: ["nhà phố", "nội thất", "hiện đại", "NHÀ BÈ"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 18,
      projectId: "HOUSE-NORMAL018",
      title: "Nhà phố LONG AN",
      clientName: "CHỊ TÚ",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "LONG AN",
      description:
        "Thiết kế nhà phố tại LONG AN với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-01.png",
      htmlContent:
        "<div><h3>Thiết Kế LONG AN</h3><p>Dự án thiết kế nhà phố tại LONG AN với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-01.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-02.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-03.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-04.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-05.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-06.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-07.png",
        "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-08.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế LONG AN",
      metaDescription: "Thiết kế nhà phố tại LONG AN",
      tags: ["nhà phố", "nội thất", "hiện đại", "LONG AN"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 19,
      projectId: "HOUSE-NORMAL019",
      title: "Nhà phố NHÀ BÈ",
      clientName: "ANH HOÀNG",
      area: "120m²",
      constructionDate: "2024-01-01",
      address: "NHÀ BÈ",
      description:
        "Thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 1.jpg",
      htmlContent:
        "<div><h3>Thiết Kế NHÀ BÈ</h3><p>Dự án thiết kế nhà phố tại NHÀ BÈ với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 1.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 2.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 3.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 4.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 5.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 6.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 7.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 8.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 9.jpg",
        "/assets/house-normal/anh Hoàng - nhà bè/NHA MAU 2 - VIEW 10.jpg",
      ],
      projectStatus: "Hoàn thành • 600 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế NHÀ BÈ",
      metaDescription: "Thiết kế nhà phố tại NHÀ BÈ",
      tags: ["nhà phố", "nội thất", "hiện đại", "NHÀ BÈ"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 20,
      projectId: "HOUSE-NORMAL020",
      title: "Nhà phố QUẬN 8",
      clientName: "CHỊ LINH",
      area: "100m²",
      constructionDate: "2024-01-01",
      address: "QUẬN 8",
      description:
        "Thiết kế nhà phố tại QUẬN 8 với phong cách hiện đại và tiện nghi.",
      category: "house-normal",
      projectCategoryId: 1,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-normal/Chị Linh - Quận 8/MAU 1-2.jpg",
      htmlContent:
        "<div><h3>Thiết Kế QUẬN 8</h3><p>Dự án thiết kế nhà phố tại QUẬN 8 với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-normal/Chị Linh - Quận 8/MAU 1-2.jpg",
        "/assets/house-normal/Chị Linh - Quận 8/MAU 1-3.jpg",
      ],
      projectStatus: "Hoàn thành • 400 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế QUẬN 8",
      metaDescription: "Thiết kế nhà phố tại QUẬN 8",
      tags: ["nhà phố", "nội thất", "hiện đại", "QUẬN 8"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
  ],
  village: [
    {
      id: 21,
      projectId: "VILLAGE021",
      title: "VILLA SUMMER",
      clientName: "VILLA SUMMER",
      area: "200m²",
      constructionDate: "2024-01-01",
      address: "QUẬN 7",
      description:
        "Thiết kế biệt thự tại QUẬN 7 với phong cách hiện đại và sang trọng.",
      category: "village",
      projectCategoryId: 3,
      style: "Hiện đại",
      thumbnailImage: "/assets/village/VILLA SUMMER - QUẬN 7/1.png",
      htmlContent:
        "<div><h3>Thiết Kế VILLA SUMMER</h3><p>Dự án thiết kế biệt thự tại QUẬN 7 với phong cách hiện đại, sang trọng và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/village/VILLA SUMMER - QUẬN 7/1.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/2.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/3.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/4.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/5.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/6.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/7.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/8.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/9.png",
        "/assets/village/VILLA SUMMER - QUẬN 7/10.png",
      ],
      projectStatus: "Hoàn thành • 1.2 tỷ",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế VILLA SUMMER",
      metaDescription: "Thiết kế biệt thự tại QUẬN 7",
      tags: ["biệt thự", "nội thất", "hiện đại", "QUẬN 7"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 22,
      projectId: "VILLAGE022",
      title: "Biệt thự vườn MAI NHẬT 1",
      clientName: "MAI NHẬT",
      area: "250m²",
      constructionDate: "2024-01-01",
      address: "MAI NHẬT",
      description:
        "Thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại và sang trọng.",
      category: "village",
      projectCategoryId: 3,
      style: "Hiện đại",
      thumbnailImage: "/assets/village/biệt thự vườn - Mai Nhat 1/1-VIEW.png",
      htmlContent:
        "<div><h3>Thiết Kế Biệt Thự Vườn MAI NHẬT 1</h3><p>Dự án thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại, sang trọng và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/village/biệt thự vườn - Mai Nhat 1/1-VIEW.png",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 01.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 02.png",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 03.png",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 03.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 05.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 06.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 07.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 1/VIEW 08.jpg",
      ],
      projectStatus: "Hoàn thành • 1.5 tỷ",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Biệt Thự Vườn MAI NHẬT 1",
      metaDescription: "Thiết kế biệt thự vườn tại MAI NHẬT",
      tags: ["biệt thự vườn", "nội thất", "hiện đại", "MAI NHẬT"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 23,
      projectId: "VILLAGE023",
      title: "Biệt thự vườn MAI NHẬT 2",
      clientName: "MAI NHẬT",
      area: "220m²",
      constructionDate: "2024-01-01",
      address: "MAI NHẬT",
      description:
        "Thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại và sang trọng.",
      category: "village",
      projectCategoryId: 3,
      style: "Hiện đại",
      thumbnailImage: "/assets/village/biệt thự vườn - Mai Nhat 2/view 01.jpg",
      htmlContent:
        "<div><h3>Thiết Kế Biệt Thự Vườn MAI NHẬT 2</h3><p>Dự án thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại, sang trọng và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/village/biệt thự vườn - Mai Nhat 2/view 01.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 2/view 02.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 2/view 03.jpg",
      ],
      projectStatus: "Hoàn thành • 1.3 tỷ",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Biệt Thự Vườn MAI NHẬT 2",
      metaDescription: "Thiết kế biệt thự vườn tại MAI NHẬT",
      tags: ["biệt thự vườn", "nội thất", "hiện đại", "MAI NHẬT"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 24,
      projectId: "VILLAGE024",
      title: "Biệt thự vườn MAI NHẬT 3",
      clientName: "MAI NHẬT",
      area: "280m²",
      constructionDate: "2024-01-01",
      address: "MAI NHẬT",
      description:
        "Thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại và sang trọng.",
      category: "village",
      projectCategoryId: 3,
      style: "Hiện đại",
      thumbnailImage: "/assets/village/biệt thự vườn - Mai Nhat 3/view 01.jpg",
      htmlContent:
        "<div><h3>Thiết Kế Biệt Thự Vườn MAI NHẬT 3</h3><p>Dự án thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại, sang trọng và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 01.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 02.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 03.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 04.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/1- view 05.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 06.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 07.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 09.jpg",
        "/assets/village/biệt thự vườn - Mai Nhat 3/view 10.jpg",
      ],
      projectStatus: "Hoàn thành • 1.8 tỷ",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Biệt Thự Vườn MAI NHẬT 3",
      metaDescription: "Thiết kế biệt thự vườn tại MAI NHẬT",
      tags: ["biệt thự vườn", "nội thất", "hiện đại", "MAI NHẬT"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 25,
      projectId: "VILLAGE025",
      title: "Biệt thự vườn MAI NHẬT - MẪU 2",
      clientName: "MAI NHẬT",
      area: "200m²",
      constructionDate: "2024-01-01",
      address: "MAI NHẬT",
      description:
        "Thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại và sang trọng.",
      category: "village",
      projectCategoryId: 3,
      style: "Hiện đại",
      thumbnailImage: "/assets/village/Mau 2 - Mai Nhat/view 01.jpg",
      htmlContent:
        "<div><h3>Thiết Kế Biệt Thự Vườn MAI NHẬT - MẪU 2</h3><p>Dự án thiết kế biệt thự vườn tại MAI NHẬT với phong cách hiện đại, sang trọng và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/village/Mau 2 - Mai Nhat/view 01.jpg",
        "/assets/village/Mau 2 - Mai Nhat/2-view 02.jpg",
        "/assets/village/Mau 2 - Mai Nhat/1-view 03.jpg",
      ],
      projectStatus: "Hoàn thành • 1.4 tỷ",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Biệt Thự Vườn MAI NHẬT - MẪU 2",
      metaDescription: "Thiết kế biệt thự vườn tại MAI NHẬT",
      tags: ["biệt thự vườn", "nội thất", "hiện đại", "MAI NHẬT"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
  ],
  "house-business": [
    {
      id: 20,
      projectId: "HOUSE-BUSINESS020",
      title: "Thương mại THE K COFFEE TEA",
      clientName: "THE K COFFEE TEA",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "THU DUC",
      description:
        "Thiết kế không gian thương mại tại THU DUC với phong cách hiện đại và tiện nghi.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-business/THE K COFFEE TEA - THU DUC/1.png",
      htmlContent:
        "<div><h3>Thiết Kế THU DUC</h3><p>Dự án thiết kế không gian thương mại tại THU DUC với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-business/THE K COFFEE TEA - THU DUC/1.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/2.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/3.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/4.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/5.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/6.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/7.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/8.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/9.png",
        "/assets/house-business/THE K COFFEE TEA - THU DUC/10.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế THU DUC",
      metaDescription: "Thiết kế không gian thương mại tại THU DUC",
      tags: ["không gian thương mại", "nội thất", "hiện đại", "THU DUC"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 21,
      projectId: "HOUSE-BUSINESS021",
      title: "Thương mại Ngoc Be Cake",
      clientName: "Ngoc Be Cake",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "Gò Vấp",
      description:
        "Thiết kế không gian thương mại tại Gò Vấp với phong cách hiện đại và tiện nghi.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-business/Ngoc Be Cake - Gò Vấp/1.png",
      htmlContent:
        "<div><h3>Thiết Kế Gò Vấp</h3><p>Dự án thiết kế không gian thương mại tại Gò Vấp với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/1.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/2.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/3.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/4.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/5.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/6.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/7.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/8.png",
        "/assets/house-business/Ngoc Be Cake - Gò Vấp/9.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Gò Vấp",
      metaDescription: "Thiết kế không gian thương mại tại Gò Vấp",
      tags: ["không gian thương mại", "nội thất", "hiện đại", "Gò Vấp"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 22,
      projectId: "HOUSE-BUSINESS022",
      title: "Thương mại B COFFEE",
      clientName: "B COFFEE",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "HCM",
      description:
        "Thiết kế không gian thương mại tại HCM với phong cách hiện đại và tiện nghi.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-business/B COFFEE - HCM/1.png",
      htmlContent:
        "<div><h3>Thiết Kế HCM</h3><p>Dự án thiết kế không gian thương mại tại HCM với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-business/B COFFEE - HCM/1.png",
        "/assets/house-business/B COFFEE - HCM/2.png",
        "/assets/house-business/B COFFEE - HCM/3.png",
        "/assets/house-business/B COFFEE - HCM/4.png",
        "/assets/house-business/B COFFEE - HCM/5.png",
        "/assets/house-business/B COFFEE - HCM/6.png",
        "/assets/house-business/B COFFEE - HCM/7.png",
        "/assets/house-business/B COFFEE - HCM/8.png",
        "/assets/house-business/B COFFEE - HCM/9.png",
        "/assets/house-business/B COFFEE - HCM/10.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế HCM",
      metaDescription: "Thiết kế không gian thương mại tại HCM",
      tags: ["không gian thương mại", "nội thất", "hiện đại", "HCM"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 23,
      projectId: "HOUSE-BUSINESS023",
      title: "Thương mại Bamboo panel",
      clientName: "Bamboo panel",
      area: "110m²",
      constructionDate: "2024-01-01",
      address: "Gò Vấp",
      description:
        "Thiết kế không gian thương mại tại Gò Vấp với phong cách hiện đại và tiện nghi.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-business/Bamboo panel - Gò Vấp/0.png",
      htmlContent:
        "<div><h3>Thiết Kế Gò Vấp</h3><p>Dự án thiết kế không gian thương mại tại Gò Vấp với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
      projectImages: [
        "/assets/house-business/Bamboo panel - Gò Vấp/0.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/1.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/2.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/3.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/5.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/6.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/7.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/8.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/9.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/10.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/11.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/12.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/13.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/14.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/15.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/19.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/20.png",
        "/assets/house-business/Bamboo panel - Gò Vấp/21.png",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Gò Vấp",
      metaDescription: "Thiết kế không gian thương mại tại Gò Vấp",
      tags: ["không gian thương mại", "nội thất", "hiện đại", "Gò Vấp"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 24,
      projectId: "HOUSE-BUSINESS024",
      title: "Văn phòng PERSEFONI",
      clientName: "PERSEFONI OFFICE",
      area: "150m²",
      constructionDate: "2024-01-01",
      address: "QUẬN 3",
      description:
        "Thiết kế văn phòng tại QUẬN 3 với phong cách hiện đại và chuyên nghiệp.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage: "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/1.png",
      htmlContent:
        "<div><h3>Thiết Kế Văn Phòng PERSEFONI</h3><p>Dự án thiết kế văn phòng tại QUẬN 3 với phong cách hiện đại, chuyên nghiệp và phù hợp với môi trường làm việc.</p></div>",
      projectImages: [
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/1.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/2.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/3.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/4.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/5.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/6.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/7.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/8.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/9.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/10.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/11.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/12.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/13.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/14.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/15.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/16.png",
        "/assets/house-business/PERSEFONI OFFICE- QUẬN 3/17.png",
      ],
      projectStatus: "Hoàn thành • 800 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Văn Phòng PERSEFONI",
      metaDescription: "Thiết kế văn phòng tại QUẬN 3",
      tags: ["văn phòng", "nội thất", "hiện đại", "QUẬN 3"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 25,
      projectId: "HOUSE-BUSINESS025",
      title: "Văn phòng VAN PHONG 89",
      clientName: "HO BA KIEN",
      area: "120m²",
      constructionDate: "2024-01-01",
      address: "HO BA KIEN",
      description:
        "Thiết kế văn phòng tại HO BA KIEN với phong cách hiện đại và chuyên nghiệp.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 01.jpg",
      htmlContent:
        "<div><h3>Thiết Kế Văn Phòng VAN PHONG 89</h3><p>Dự án thiết kế văn phòng tại HO BA KIEN với phong cách hiện đại, chuyên nghiệp và phù hợp với môi trường làm việc.</p></div>",
      projectImages: [
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 01.jpg",
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 02.jpg",
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 03.jpg",
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 04.jpg",
        "/assets/house-business/VAN PHONG 89 - HO BA KIEN/view 05.jpg",
      ],
      projectStatus: "Hoàn thành • 600 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Văn Phòng VAN PHONG 89",
      metaDescription: "Thiết kế văn phòng tại HO BA KIEN",
      tags: ["văn phòng", "nội thất", "hiện đại", "HO BA KIEN"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
    {
      id: 26,
      projectId: "HOUSE-BUSINESS026",
      title: "Văn phòng WEPLOY",
      clientName: "WEPLOY OFFICE",
      area: "100m²",
      constructionDate: "2024-01-01",
      address: "Quận 1",
      description:
        "Thiết kế văn phòng tại Quận 1 với phong cách hiện đại và chuyên nghiệp.",
      category: "house-business",
      projectCategoryId: 4,
      style: "Hiện đại",
      thumbnailImage:
        "/assets/house-business/WEPLOY OFFICE - Quận 1/VIEW 01.jpg",
      htmlContent:
        "<div><h3>Thiết Kế Văn Phòng WEPLOY</h3><p>Dự án thiết kế văn phòng tại Quận 1 với phong cách hiện đại, chuyên nghiệp và phù hợp với môi trường làm việc.</p></div>",
      projectImages: [
        "/assets/house-business/WEPLOY OFFICE - Quận 1/VIEW 01.jpg",
        "/assets/house-business/WEPLOY OFFICE - Quận 1/VIEW 02.jpg",
        "/assets/house-business/WEPLOY OFFICE - Quận 1/VIEW 03.jpg",
      ],
      projectStatus: "Hoàn thành • 500 triệu",
      completionDate: "2024-06-30",
      architectName: "KTS. PG Design",
      contractorName: "PG Design",
      metaTitle: "Thiết Kế Văn Phòng WEPLOY",
      metaDescription: "Thiết kế văn phòng tại Quận 1",
      tags: ["văn phòng", "nội thất", "hiện đại", "Quận 1"],
      isOnHomePage: false,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-06-30T00:00:00Z",
    },
  ],
};

// Helper function to get all projects by category
export const getProjectsByCategory = (category: string): ProjectDetail[] => {
  switch (category) {
    case "appartment":
      return additionalProjectData.appartment;
    case "house-normal":
      return additionalProjectData["house-normal"];
    case "village":
      return additionalProjectData.village;
    case "house-business":
      return additionalProjectData["house-business"];
    default:
      return [];
  }
};

// Helper function to get all projects
export const getAllProjects = (): ProjectDetail[] => {
  return [
    ...additionalProjectData.appartment,
    ...additionalProjectData["house-normal"],
    ...additionalProjectData.village,
    ...additionalProjectData["house-business"],
  ];
};

// Helper function to get project by ID
export const getProjectById = (id: number): ProjectDetail | undefined => {
  const allProjects = getAllProjects();
  return allProjects.find((project) => project.id === id);
};

// Helper function to get project by project ID
export const getProjectByProjectId = (
  projectId: string
): ProjectDetail | undefined => {
  const allProjects = getAllProjects();
  return allProjects.find((project) => project.projectId === projectId);
};
