// Auto-generated project data from images (Updated with correct image paths)
// Generated on: 2025-07-23T10:44:02.309Z

import { ProjectDetail } from '../types/projectCategoryPageTypes';

export const additionalProjectData: {
  appartment: ProjectDetail[];
  "house-normal": ProjectDetail[];
  village: ProjectDetail[];
  "house-business": ProjectDetail[];
} = {
  appartment: [
  {
    "id": 1,
    "projectId": "APT001",
    "title": "Thiết Kế Nội Thất Căn Hộ PICITY Q12",
    "clientName": "Khách hàng PICITY Q12",
    "area": "85m²",
    "constructionDate": "2024-01-15",
    "address": "PICITY Q12, Quận 12, TP.HCM",
    "description": "Thiết kế nội thất căn hộ hiện đại tại dự án PICITY Q12 với phong cách tối giản và tối ưu không gian.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại tối giản",
    "thumbnailImage": "/assets/appartment/PICITY Q12/picity-q12-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Căn Hộ PICITY Q12</h3><p>Dự án thiết kế nội thất căn hộ tại dự án PICITY Q12 với phong cách hiện đại tối giản, tối ưu không gian sống cho gia đình trẻ.</p></div>",
    "projectImages": [
      "/assets/appartment/PICITY Q12/picity-q12-01.png",
      "/assets/appartment/PICITY Q12/picity-q12-02.png",
      "/assets/appartment/PICITY Q12/picity-q12-03.png",
      "/assets/appartment/PICITY Q12/picity-q12-04.png",
      "/assets/appartment/PICITY Q12/picity-q12-05.png",
      "/assets/appartment/PICITY Q12/picity-q12-06.png",
      "/assets/appartment/PICITY Q12/picity-q12-07.png",
      "/assets/appartment/PICITY Q12/picity-q12-08.png",
      "/assets/appartment/PICITY Q12/picity-q12-09.png",
      "/assets/appartment/PICITY Q12/picity-q12-10.png",
      "/assets/appartment/PICITY Q12/picity-q12-11.png",
      "/assets/appartment/PICITY Q12/picity-q12-12.png",
      "/assets/appartment/PICITY Q12/picity-q12-13.png",
      "/assets/appartment/PICITY Q12/picity-q12-14.png"
    ],
    "projectStatus": "Hoàn thành • 350 triệu",
    "completionDate": "2024-03-30",
    "architectName": "KTS. Nguyễn Văn A",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Căn Hộ PICITY Q12",
    "metaDescription": "Thiết kế nội thất căn hộ hiện đại tại PICITY Q12 với phong cách tối giản",
    "tags": [
      "căn hộ",
      "nội thất",
      "hiện đại",
      "PICITY"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-01-15T00:00:00Z",
    "updatedAt": "2024-03-30T00:00:00Z"
  },
  {
    "id": 2,
    "projectId": "APT002",
    "title": "Thiết Kế Nội Thất Opal Garden",
    "clientName": "Chị Phương",
    "area": "120m²",
    "constructionDate": "2024-02-01",
    "address": "Opal Garden, Quận 7, TP.HCM",
    "description": "Thiết kế nội thất căn hộ cao cấp tại Opal Garden với phong cách sang trọng và hiện đại.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại sang trọng",
    "thumbnailImage": "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Opal Garden</h3><p>Dự án thiết kế nội thất căn hộ cao cấp tại Opal Garden với phong cách sang trọng, sử dụng vật liệu cao cấp và ánh sáng tự nhiên.</p></div>",
    "projectImages": [
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-01.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-02.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-03.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-04.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-05.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-06.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-07.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-08.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-09.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-10.png",
      "/assets/appartment/CHỊ PHƯƠNG - OPAL GARDEN/opal-garden-11.png"
    ],
    "projectStatus": "Hoàn thành • 450 triệu",
    "completionDate": "2024-04-15",
    "architectName": "KTS. Trần Thị B",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Opal Garden",
    "metaDescription": "Thiết kế nội thất căn hộ cao cấp tại Opal Garden",
    "tags": [
      "căn hộ",
      "nội thất",
      "sang trọng",
      "Opal Garden"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-02-01T00:00:00Z",
    "updatedAt": "2024-04-15T00:00:00Z"
  },
  {
    "id": 3,
    "projectId": "APT003",
    "title": "Thiết Kế Nội Thất Opal Skyline",
    "clientName": "Mr. Lượng",
    "area": "95m²",
    "constructionDate": "2024-02-15",
    "address": "Opal Skyline, Quận 2, TP.HCM",
    "description": "Thiết kế nội thất căn hộ view đẹp tại Opal Skyline với không gian mở và ánh sáng tự nhiên.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại view đẹp",
    "thumbnailImage": "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Opal Skyline</h3><p>Dự án thiết kế nội thất căn hộ tại Opal Skyline với view đẹp, không gian mở và tối ưu ánh sáng tự nhiên.</p></div>",
    "projectImages": [
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-01.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-02.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-03.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-04.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-05.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-06.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-07.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-08.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-09.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-10.png",
      "/assets/appartment/Mr.Lượng - Opal Skyline/opal-skyline-11.png"
    ],
    "projectStatus": "Hoàn thành • 380 triệu",
    "completionDate": "2024-05-01",
    "architectName": "KTS. Lê Văn C",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Opal Skyline",
    "metaDescription": "Thiết kế nội thất căn hộ view đẹp tại Opal Skyline",
    "tags": [
      "căn hộ",
      "nội thất",
      "view đẹp",
      "Opal Skyline"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-02-15T00:00:00Z",
    "updatedAt": "2024-05-01T00:00:00Z"
  },
  {
    "id": 4,
    "projectId": "APT004",
    "title": "Thiết Kế Nội Thất Phú Gia Hưng",
    "clientName": "Anh Đăng",
    "area": "110m²",
    "constructionDate": "2024-03-01",
    "address": "Phú Gia Hưng, Gò Vấp, TP.HCM",
    "description": "Thiết kế nội thất căn hộ gia đình tại Phú Gia Hưng với không gian ấm cúng và tiện nghi.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại gia đình",
    "thumbnailImage": "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Phú Gia Hưng</h3><p>Dự án thiết kế nội thất căn hộ gia đình tại Phú Gia Hưng với không gian ấm cúng, tiện nghi và phù hợp với nhu cầu gia đình.</p></div>",
    "projectImages": [
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-01.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-02.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-03.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-04.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-05.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-06.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-07.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-08.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-09.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-10.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-11.png",
      "/assets/appartment/ANH ĐĂNG - PHÚ GIA HƯNG - GÒ VẤP/phu-gia-hung-12.png"
    ],
    "projectStatus": "Hoàn thành • 420 triệu",
    "completionDate": "2024-05-30",
    "architectName": "KTS. Phạm Thị D",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Phú Gia Hưng",
    "metaDescription": "Thiết kế nội thất căn hộ gia đình tại Phú Gia Hưng",
    "tags": [
      "căn hộ",
      "nội thất",
      "gia đình",
      "Phú Gia Hưng"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-03-01T00:00:00Z",
    "updatedAt": "2024-05-30T00:00:00Z"
  },
  {
    "id": 5,
    "projectId": "APT005",
    "title": "Thiết Kế Nội Thất Diamond Center",
    "clientName": "Hoàng Nhi",
    "area": "130m²",
    "constructionDate": "2024-03-15",
    "address": "Diamond Center, Quận 1, TP.HCM",
    "description": "Thiết kế nội thất căn hộ cao cấp tại Diamond Center với phong cách luxury và hiện đại.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Luxury hiện đại",
    "thumbnailImage": "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Diamond Center</h3><p>Dự án thiết kế nội thất căn hộ cao cấp tại Diamond Center với phong cách luxury, sử dụng vật liệu cao cấp và thiết kế độc đáo.</p></div>",
    "projectImages": [
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-01.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-02.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-03.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-04.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-05.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-06.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-07.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-08.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-09.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-10.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-11.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-12.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-13.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-14.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-15.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-16.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-17.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-18.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-19.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-20.png",
      "/assets/appartment/HOÀNG NHI - DIAMOND CENTERY/diamond-center-21.png"
    ],
    "projectStatus": "Hoàn thành • 550 triệu",
    "completionDate": "2024-06-15",
    "architectName": "KTS. Hoàng Văn E",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Diamond Center",
    "metaDescription": "Thiết kế nội thất căn hộ cao cấp tại Diamond Center",
    "tags": [
      "căn hộ",
      "nội thất",
      "luxury",
      "Diamond Center"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-03-15T00:00:00Z",
    "updatedAt": "2024-06-15T00:00:00Z"
  },
  {
    "id": 6,
    "projectId": "APT006",
    "title": "Thiết Kế Nội Thất Cityland Park Hill",
    "clientName": "Anh Tuấn",
    "area": "100m²",
    "constructionDate": "2024-04-01",
    "address": "Cityland Park Hill, Quận 7, TP.HCM",
    "description": "Thiết kế nội thất căn hộ tại Cityland Park Hill với không gian xanh và view công viên.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại xanh",
    "thumbnailImage": "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Cityland Park Hill</h3><p>Dự án thiết kế nội thất căn hộ tại Cityland Park Hill với không gian xanh, view công viên và thiết kế thân thiện môi trường.</p></div>",
    "projectImages": [
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-01.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-02.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-03.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-04.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-05.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-06.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-07.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-08.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-09.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-10.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-11.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-12.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-13.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-14.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-15.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-16.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-17.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-18.png",
      "/assets/appartment/ANH TUẤN - CITYLAND PARK HILL/cityland-park-hill-19.png"
    ],
    "projectStatus": "Đang thi công • 400 triệu",
    "architectName": "KTS. Trần Thị F",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Cityland Park Hill",
    "metaDescription": "Thiết kế nội thất căn hộ tại Cityland Park Hill",
    "tags": [
      "căn hộ",
      "nội thất",
      "xanh",
      "Cityland"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-04-01T00:00:00Z",
    "updatedAt": "2024-04-01T00:00:00Z"
  },
  {
    "id": 7,
    "projectId": "APT007",
    "title": "Thiết Kế Nội Thất Bình Dương",
    "clientName": "Anh Hoàng",
    "area": "140m²",
    "constructionDate": "2024-04-15",
    "address": "Bình Dương",
    "description": "Thiết kế nội thất căn hộ tại Bình Dương với không gian rộng rãi và tiện nghi hiện đại.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại rộng rãi",
    "thumbnailImage": "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Bình Dương</h3><p>Dự án thiết kế nội thất căn hộ tại Bình Dương với không gian rộng rãi, tiện nghi hiện đại và phù hợp với khí hậu địa phương.</p></div>",
    "projectImages": [
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-01.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-02.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-03.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-04.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-05.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-06.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-07.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-08.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-09.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-10.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-11.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-12.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-13.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-14.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-15.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-16.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-17.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-18.png",
      "/assets/appartment/ANH HOÀNG - BÌNH DƯƠNG/binh-duong-19.png"
    ],
    "projectStatus": "Hoàn thành • 480 triệu",
    "completionDate": "2024-07-01",
    "architectName": "KTS. Nguyễn Văn G",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Bình Dương",
    "metaDescription": "Thiết kế nội thất căn hộ tại Bình Dương",
    "tags": [
      "căn hộ",
      "nội thất",
      "Bình Dương",
      "rộng rãi"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-04-15T00:00:00Z",
    "updatedAt": "2024-07-01T00:00:00Z"
  },
  {
    "id": 8,
    "projectId": "APT008",
    "title": "Thiết Kế Nội Thất Căn Hộ Gia Đình",
    "clientName": "Anh Tùng - Chị Thu",
    "area": "115m²",
    "constructionDate": "2024-05-01",
    "address": "Quận 7, TP.HCM",
    "description": "Thiết kế nội thất căn hộ gia đình với không gian ấm cúng và tiện nghi cho trẻ em.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại gia đình",
    "thumbnailImage": "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Căn Hộ Gia Đình</h3><p>Dự án thiết kế nội thất căn hộ gia đình với không gian ấm cúng, tiện nghi cho trẻ em và phù hợp với nhu cầu gia đình hiện đại.</p></div>",
    "projectImages": [
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-01.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-02.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-03.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-04.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-05.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-06.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-07.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-08.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-09.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-10.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-11.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-12.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-13.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-14.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-15.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-16.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-17.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-18.png",
      "/assets/appartment/ANH TÙNG - CHỊ THU/can-ho-gia-dinh-19.png"
    ],
    "projectStatus": "Hoàn thành • 430 triệu",
    "completionDate": "2024-07-15",
    "architectName": "KTS. Lê Thị H",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Căn Hộ Gia Đình",
    "metaDescription": "Thiết kế nội thất căn hộ gia đình tại Quận 7",
    "tags": [
      "căn hộ",
      "nội thất",
      "gia đình",
      "trẻ em"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-05-01T00:00:00Z",
    "updatedAt": "2024-07-15T00:00:00Z"
  },
  {
    "id": 9,
    "projectId": "APT009",
    "title": "Thiết Kế Nội Thất Pegasuite",
    "clientName": "Chị Hà",
    "area": "125m²",
    "constructionDate": "2024-05-15",
    "address": "Pegasuite, Quận 8, TP.HCM",
    "description": "Thiết kế nội thất căn hộ tại Pegasuite với phong cách hiện đại và tối ưu không gian.",
    "category": "appartment",
    "projectCategoryId": 2,
    "style": "Hiện đại tối ưu",
    "thumbnailImage": "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nội Thất Pegasuite</h3><p>Dự án thiết kế nội thất căn hộ tại Pegasuite với phong cách hiện đại, tối ưu không gian và sử dụng vật liệu thông minh.</p></div>",
    "projectImages": [
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-01.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-02.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-03.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-04.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-05.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-06.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-07.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-08.png",
      "/assets/appartment/CHỊ HÀ - PEGASUITE - QUẬN 8/pegasuite-09.png"
    ],
    "projectStatus": "Đang thi công • 460 triệu",
    "architectName": "KTS. Phạm Văn I",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nội Thất Pegasuite",
    "metaDescription": "Thiết kế nội thất căn hộ tại Pegasuite Quận 8",
    "tags": [
      "căn hộ",
      "nội thất",
      "Pegasuite",
      "tối ưu"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-05-15T00:00:00Z",
    "updatedAt": "2024-05-15T00:00:00Z"
  }
],
  "house-normal": [
  {
    "id": 10,
    "projectId": "HN001",
    "title": "Thiết Kế Nhà Phố Long An",
    "clientName": "Chị Tú",
    "area": "5x20m",
    "constructionDate": "2024-01-01",
    "address": "Long An",
    "description": "Thiết kế nhà phố hiện đại tại Long An với không gian mở và ánh sáng tự nhiên.",
    "category": "house-normal",
    "projectCategoryId": 1,
    "style": "Hiện đại",
    "thumbnailImage": "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nhà Phố Long An</h3><p>Dự án thiết kế nhà phố hiện đại tại Long An với không gian mở, ánh sáng tự nhiên và tối ưu diện tích sử dụng.</p></div>",
    "projectImages": [
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-01.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-02.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-03.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-04.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-05.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-06.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-07.png",
      "/assets/house-normal/CHỊ TÚ - LONG AN/nha-pho-long-an-08.png"
    ],
    "projectStatus": "Hoàn thành • 2.8 tỷ",
    "completionDate": "2024-06-30",
    "architectName": "KTS. Nguyễn Văn A",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nhà Phố Long An",
    "metaDescription": "Thiết kế nhà phố hiện đại tại Long An",
    "tags": [
      "nhà phố",
      "hiện đại",
      "Long An",
      "5x20m"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-01-01T00:00:00Z",
    "updatedAt": "2024-06-30T00:00:00Z"
  },
  {
    "id": 11,
    "projectId": "HN002",
    "title": "Thiết Kế Nhà Phố Nhà Bè",
    "clientName": "Khách hàng Nhà Bè",
    "area": "4x18m",
    "constructionDate": "2024-02-01",
    "address": "Nhà Bè, TP.HCM",
    "description": "Thiết kế nhà phố tại Nhà Bè với phong cách hiện đại và tối ưu không gian.",
    "category": "house-normal",
    "projectCategoryId": 1,
    "style": "Hiện đại tối ưu",
    "thumbnailImage": "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nhà Phố Nhà Bè</h3><p>Dự án thiết kế nhà phố tại Nhà Bè với phong cách hiện đại, tối ưu không gian và phù hợp với khí hậu địa phương.</p></div>",
    "projectImages": [
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-01.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-02.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-03.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-04.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-05.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-06.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-07.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-08.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-09.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-10.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-11.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-12.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-13.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-14.png",
      "/assets/house-normal/NHÀ BÈ/nha-pho-nha-be-15.png"
    ],
    "projectStatus": "Hoàn thành • 2.2 tỷ",
    "completionDate": "2024-07-15",
    "architectName": "KTS. Trần Thị B",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nhà Phố Nhà Bè",
    "metaDescription": "Thiết kế nhà phố tại Nhà Bè",
    "tags": [
      "nhà phố",
      "hiện đại",
      "Nhà Bè",
      "4x18m"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-02-01T00:00:00Z",
    "updatedAt": "2024-07-15T00:00:00Z"
  },
  {
    "id": 12,
    "projectId": "HN003",
    "title": "Thiết Kế Nhà Phố Indochine",
    "clientName": "Khách hàng Indochine",
    "area": "6x22m",
    "constructionDate": "2024-03-01",
    "address": "Long An",
    "description": "Thiết kế nhà phố phong cách Indochine tại Long An với kiến trúc độc đáo.",
    "category": "house-normal",
    "projectCategoryId": 1,
    "style": "Indochine",
    "thumbnailImage": "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nhà Phố Indochine</h3><p>Dự án thiết kế nhà phố phong cách Indochine tại Long An với kiến trúc độc đáo, kết hợp giữa truyền thống và hiện đại.</p></div>",
    "projectImages": [
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-01.png",
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-02.png",
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-03.png",
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-04.png",
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-05.png",
      "/assets/house-normal/LONG AN - INDOCHINE/nha-pho-indochine-06.png"
    ],
    "projectStatus": "Hoàn thành • 3.5 tỷ",
    "completionDate": "2024-08-01",
    "architectName": "KTS. Lê Văn C",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nhà Phố Indochine",
    "metaDescription": "Thiết kế nhà phố phong cách Indochine tại Long An",
    "tags": [
      "nhà phố",
      "Indochine",
      "Long An",
      "6x22m"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-03-01T00:00:00Z",
    "updatedAt": "2024-08-01T00:00:00Z"
  },
  {
    "id": 13,
    "projectId": "HN004",
    "title": "Thiết Kế Nhà Phố Ms. Hương",
    "clientName": "Ms. Hương",
    "area": "5x19m",
    "constructionDate": "2024-04-01",
    "address": "TP.HCM",
    "description": "Thiết Kế nhà phố cho Ms. Hương với phong cách hiện đại và tiện nghi.",
    "category": "house-normal",
    "projectCategoryId": 1,
    "style": "Hiện đại tiện nghi",
    "thumbnailImage": "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nhà Phố Ms. Hương</h3><p>Dự án thiết kế nhà phố cho Ms. Hương với phong cách hiện đại, tiện nghi và phù hợp với nhu cầu sử dụng.</p></div>",
    "projectImages": [
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-01.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-02.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-03.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-04.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-05.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-06.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-07.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-08.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-09.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-10.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-11.png",
      "/assets/house-normal/MS.HƯƠNG/nha-pho-ms-huong-12.png"
    ],
    "projectStatus": "Đang thi công • 2.6 tỷ",
    "architectName": "KTS. Phạm Thị D",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nhà Phố Ms. Hương",
    "metaDescription": "Thiết kế nhà phố cho Ms. Hương",
    "tags": [
      "nhà phố",
      "hiện đại",
      "tiện nghi",
      "5x19m"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-04-01T00:00:00Z",
    "updatedAt": "2024-04-01T00:00:00Z"
  },
  {
    "id": 14,
    "projectId": "HN005",
    "title": "Thiết Kế Nhà Phố Long Thành",
    "clientName": "Khách hàng Long Thành",
    "area": "6x20m",
    "constructionDate": "2024-05-01",
    "address": "Long Thành, Đồng Nai",
    "description": "Thiết kế nhà phố tại Long Thành với không gian rộng rãi và hiện đại.",
    "category": "house-normal",
    "projectCategoryId": 1,
    "style": "Hiện đại rộng rãi",
    "thumbnailImage": "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-01.png",
    "htmlContent": "<div><h3>Thiết Kế Nhà Phố Long Thành</h3><p>Dự án thiết kế nhà phố tại Long Thành với không gian rộng rãi, hiện đại và phù hợp với khí hậu địa phương.</p></div>",
    "projectImages": [
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-01.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-02.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-03.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-04.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-05.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-06.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-07.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-08.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-09.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-10.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-11.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-12.png",
      "/assets/house-normal/LONG THÀNH/nha-pho-long-thanh-13.png"
    ],
    "projectStatus": "Hoàn thành • 3.2 tỷ",
    "completionDate": "2024-09-01",
    "architectName": "KTS. Hoàng Văn E",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Nhà Phố Long Thành",
    "metaDescription": "Thiết kế nhà phố tại Long Thành",
    "tags": [
      "nhà phố",
      "hiện đại",
      "Long Thành",
      "6x20m"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-05-01T00:00:00Z",
    "updatedAt": "2024-09-01T00:00:00Z"
  }
],
  village: [
  {
    "id": 15,
    "projectId": "VL001",
    "title": "Thiết Kế Molar Villa",
    "clientName": "Khách hàng Molar Villa",
    "area": "8x25m",
    "constructionDate": "2024-01-15",
    "address": "Quận 9, TP.HCM",
    "description": "Thiết kế biệt thự Molar Villa tại Quận 9 với kiến trúc độc đáo và không gian sang trọng.",
    "category": "village",
    "projectCategoryId": 3,
    "style": "Biệt thự sang trọng",
    "thumbnailImage": "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-01.png",
    "htmlContent": "<div><h3>Thiết Kế Molar Villa</h3><p>Dự án thiết kế biệt thự Molar Villa tại Quận 9 với kiến trúc độc đáo, không gian sang trọng và tiện nghi cao cấp.</p></div>",
    "projectImages": [
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-01.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-02.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-03.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-04.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-05.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-06.png",
      "/assets/village/MOLAR VILLA - QUẬN 9/molar-villa-07.png"
    ],
    "projectStatus": "Hoàn thành • 8.5 tỷ",
    "completionDate": "2024-08-15",
    "architectName": "KTS. Nguyễn Văn A",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Molar Villa",
    "metaDescription": "Thiết kế biệt thự Molar Villa tại Quận 9",
    "tags": [
      "biệt thự",
      "sang trọng",
      "Quận 9",
      "8x25m"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-01-15T00:00:00Z",
    "updatedAt": "2024-08-15T00:00:00Z"
  },
  {
    "id": 16,
    "projectId": "VL002",
    "title": "Thiết Kế Sky Linked Villa",
    "clientName": "Khách hàng Sky Linked",
    "area": "10x30m",
    "constructionDate": "2024-03-01",
    "address": "TP.HCM",
    "description": "Thiết kế biệt thự Sky Linked Villa với kiến trúc hiện đại và view đẹp.",
    "category": "village",
    "projectCategoryId": 3,
    "style": "Biệt thự hiện đại",
    "thumbnailImage": "/assets/village/SKY LINKED VILLA/sky-linked-villa-01.png",
    "htmlContent": "<div><h3>Thiết Kế Sky Linked Villa</h3><p>Dự án thiết kế biệt thự Sky Linked Villa với kiến trúc hiện đại, view đẹp và không gian sống cao cấp.</p></div>",
    "projectImages": [
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-01.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-02.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-03.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-04.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-05.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-06.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-07.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-08.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-09.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-10.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-11.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-12.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-13.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-14.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-15.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-16.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-17.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-18.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-19.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-20.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-21.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-22.png",
      "/assets/village/SKY LINKED VILLA/sky-linked-villa-23.png"
    ],
    "projectStatus": "Hoàn thành • 12 tỷ",
    "completionDate": "2024-10-01",
    "architectName": "KTS. Trần Thị B",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Sky Linked Villa",
    "metaDescription": "Thiết kế biệt thự Sky Linked Villa",
    "tags": [
      "biệt thự",
      "hiện đại",
      "view đẹp",
      "10x30m"
    ],
    "isOnHomePage": true,
    "isActive": true,
    "createdAt": "2024-03-01T00:00:00Z",
    "updatedAt": "2024-10-01T00:00:00Z"
  },
  {
    "id": 17,
    "projectId": "VL003",
    "title": "Thiết Kế Villa Summer",
    "clientName": "Khách hàng Villa Summer",
    "area": "12x35m",
    "constructionDate": "2024-05-01",
    "address": "TP.HCM",
    "description": "Thiết kế biệt thự Villa Summer với phong cách mùa hè và không gian thoáng đãng.",
    "category": "village",
    "projectCategoryId": 3,
    "style": "Biệt thự mùa hè",
    "thumbnailImage": "/assets/village/VILLA SUMMER/villa-summer-01.png",
    "htmlContent": "<div><h3>Thiết Kế Villa Summer</h3><p>Dự án thiết kế biệt thự Villa Summer với phong cách mùa hè, không gian thoáng đãng và tiện nghi cao cấp.</p></div>",
    "projectImages": [
      "/assets/village/VILLA SUMMER/villa-summer-01.png",
      "/assets/village/VILLA SUMMER/villa-summer-02.png",
      "/assets/village/VILLA SUMMER/villa-summer-03.png",
      "/assets/village/VILLA SUMMER/villa-summer-04.png",
      "/assets/village/VILLA SUMMER/villa-summer-05.png",
      "/assets/village/VILLA SUMMER/villa-summer-06.png",
      "/assets/village/VILLA SUMMER/villa-summer-07.png",
      "/assets/village/VILLA SUMMER/villa-summer-08.png",
      "/assets/village/VILLA SUMMER/villa-summer-09.png"
    ],
    "projectStatus": "Đang thi công • 15 tỷ",
    "architectName": "KTS. Lê Văn C",
    "contractorName": "PG Design",
    "metaTitle": "Thiết Kế Villa Summer",
    "metaDescription": "Thiết kế biệt thự Villa Summer",
    "tags": [
      "biệt thự",
      "mùa hè",
      "thoáng đãng",
      "12x35m"
    ],
    "isOnHomePage": false,
    "isActive": true,
    "createdAt": "2024-05-01T00:00:00Z",
    "updatedAt": "2024-05-01T00:00:00Z"
  }
],
  "house-business": []
};

// Helper function to get all projects by category
export const getProjectsByCategory = (category: string): ProjectDetail[] => {
  switch (category) {
    case 'appartment':
      return additionalProjectData.appartment;
    case 'house-normal':
      return additionalProjectData["house-normal"];
    case 'village':
      return additionalProjectData.village;
    case 'house-business':
      return additionalProjectData["house-business"];
    default:
      return [];
  }
};

// Helper function to get all projects
export const getAllProjects = (): ProjectDetail[] => {
  return [
    ...additionalProjectData.appartment,
    ...additionalProjectData["house-normal"],
    ...additionalProjectData.village,
    ...additionalProjectData["house-business"]
  ];
};

// Helper function to get project by ID
export const getProjectById = (id: number): ProjectDetail | undefined => {
  const allProjects = getAllProjects();
  return allProjects.find(project => project.id === id);
};

// Helper function to get project by project ID
export const getProjectByProjectId = (projectId: string): ProjectDetail | undefined => {
  const allProjects = getAllProjects();
  return allProjects.find(project => project.projectId === projectId);
};